
language: c
script: cmake . && make
dist: xenial

matrix:
  include:
    - os: osx
      osx_image: xcode7.3

    - os: osx
      osx_image: xcode8.3

    - os: osx
      osx_image: xcode9

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="export CC=gcc-4.9"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="export CC=gcc-5"

    - os: linux
      env:
        - MATRIX_EVAL="echo GCC 6 should be used by default"
 
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="export CC=gcc-7"
 
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="export CC=gcc-8"
 
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="export CC=clang-3.9"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="export CC=clang-4.0"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="export CC=clang-5.0"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="export CC=clang-6.0"
    
    - os: windows
      addons:
        chocolatey:
            packages:
                visualstudio2017buildtools
      script: cmake -G "Visual Studio 15 2017" . && cmake --build .

    - os: windows
      addons:
        chocolatey:
            packages:
                mingw
      script: cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" . && cmake --build .

before_install:
- eval "${MATRIX_EVAL}"
